Q1.: Consider the following situation and state which test statistics and hypotheses test can be used.
Suppose we observe samples from a normal distribution, where the variance is unknown. We want
to check whether the mean is greater than μ. What test statistics and test can be applied for this
situation?


As per the given condition, we can use T-test (more specifically one tailed T-Test) because of the following reason:
1.	Variance is unknown, means relatively STD is also unknown.
2.	Normal distribution of the data, which is one of the assumption for T-test.
3.	One tailed because we want to check the relationship between variable in a single direction i.e., either left or right and are not looking for any specific value.  


Q2.: The density function of a continuous random variable X is given by

fX(x) = {
k − x, 0 < x < 1,
0, otherwise.

Find the value of k, FX(0.5)?


In [ ]:
import sympy as sp

# Define the symbol x and the constant k
x = sp.symbols('x')
k = sp.symbols('k')

# Define the PDF f_X(x)
f_X = k - x

# Define the limits of integration
a = 0
b = 1

# Calculate the integral of f_X(x) from 0 to 1
integral = sp.integrate(f_X, (x, a, b))

# Set up the equation to solve for k: Integral = 1 (PDF must integrate to 1)
equation = sp.Eq(integral, 1)

# Solve for k
solutions = sp.solve(equation, k)

# Calculate the CDF F_X(0.5) using the computed k
cdf_x = sp.integrate(f_X, (x, a, 0.5)).subs(k, solutions[0])

# Print the value of k and F_X(0.5)
print("Value of k:", solutions[0])
print("F_X(0.5):", cdf_x)


Value of k: 3/2
F_X(0.5): 0.625000000000000


Q3.: A factory has a machine that dispenses 98.5 ml of liquid in a bottle. An employee believes that
the average amount of liquid in a bottle is less than 98.5 ml. He took a sample of 100 random bottles
from the factory and found out that the average amount of liquid in a bottle is 98.29 ml with a
standard deviation of 1.2 ml. Define Null and Alternate Hypothesis and at which level of significance
we have to accept Null hypothesis.


1. Null Hypothesis (H0): The average amount of liquid in each bottle is equal to or greater than 98.5 ml.
2. Alternative Hypothesis (Ha): The average amount of liquid in each bottle is less than 98.5 ml.
3.	Level of significance (alpha) = 0.05 (i.e. 5%)

Q4: A six sided die is marked ‘1’ on one face, ‘2’ on two of its faces, and ‘3’ on the remaining three
faces. The die is thrown twice. Let X denotes the total score in two throws. What is the PMF for X.


In [ ]:
# Define the possible values of X and their probabilities
pmf = {
    2: 1/36,
    3: 4/36,
    4: 9/36,
    5: 12/36,
    6: 9/36
}

# Display the PMF
for value, probability in pmf.items():
    print(f'P(X = {value}) = {probability:.4f}')


P(X = 2) = 0.0278
P(X = 3) = 0.1111
P(X = 4) = 0.2500
P(X = 5) = 0.3333
P(X = 6) = 0.2500


Q5.: A pharmaceutical company is testing a new drug. The probability that a patient experiencing a
side effect from this drug is 0.10. If the drug is given to 5 patients, what is the probability that more
than 1 patient will experience the side effect


In [ ]:
from scipy.stats import binom

# Given data
p = 0.10  # Probability of side effect
n = 5     # Number of patients

# Calculate the probabilities for k = 2, 3, 4, 5
prob_more_than_1 = sum(binom.pmf(k, n, p,) for k in range(2, n + 1))

print("Probability that more than 1 patient will experience the side effect:", prob_more_than_1)


Probability that more than 1 patient will experience the side effect: 0.08145999999999992


Q6: Find the Eigen Vectors of the matrix A.

A = [

1 1 −2

−1 2 1

0 1 −1

]


In [ ]:
from numpy.linalg import eig

a = np.array([[1,1,-2],[-1,2,1],[0,1,-1]])
value, vector = eig(a)

print('Eigen value :\n',value)
print('\nEigen vector :\n', vector)

Eigen value :
 [ 2.  1. -1.]

Eigen vector :
 [[ 3.01511345e-01 -8.01783726e-01  7.07106781e-01]
 [ 9.04534034e-01 -5.34522484e-01 -2.24345647e-16]
 [ 3.01511345e-01 -2.67261242e-01  7.07106781e-01]]


Q7: Find the IQR of the data : 15,21,41,25 and 19.


In [ ]:
data = [15,21,51,25,19]

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print('IQR :', q3-q1)

IQR : 6.0


Q8: Find Mean, Median and Mode of the following data?

Class Interval

0-10 10-20 20-30 30-40 40-50 50-60 60-70

Frequency

8 12 10 8 3 2 7


In [ ]:
from statistics import mean, median, mode

c_i = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70']
f_i = [8, 12, 10, 8, 3, 2, 7]

mid =  [(int(i.split('-')[0]) + int(i.split('-')[1])) / 2 for i in c_i]

da = []
for j in range(len(c_i)):
  da.extend([mid[j]] *f_i[j])

print('Mean :', mean(da))
print('Median :', median(da))
print('Mode :', mode(da))

Mean : 29.0
Median : 25.0
Mode : 15.0


Q9.: Find the Karl Persons Coefficient of Correlation for the following data:

Measurement

10 11 12 13 14 15

Frequency

2 4 10 8 5 1


In [ ]:
Measurement = [10, 11, 12, 13, 14, 15]
Frequency = [2, 4, 10, 8, 5, 1]

print('Coefficient of Correlation :',np.corrcoef(Measurement, Frequency)[0,1])

Coefficient of Correlation : -0.06172133998483677



Q10.: A company has two plants to manufacture scooters. Plant-I manufactures 80% of the scooters
and plant -II manufactures20%. At plant-I 85 out of 100 scooters are rated standard quality or better.
At plant -II, only 65 out of 100 scooters are rated standard quality or better. What is the probability
scooter selected at random came from plant -I , if it is known that the scooter is of standard quality?



In [ ]:
# Given probabilities
P_Plant_I = 0.80
P_Plant_II = 0.20
P_Standard_Quality_Plant_I = 0.85
P_Standard_Quality_Plant_II = 0.65

# Calculate P(Standard Quality)
P_Standard_Quality = (P_Standard_Quality_Plant_I * P_Plant_I) + (P_Standard_Quality_Plant_II * P_Plant_II)

# Calculate P(Plant-I | Standard Quality) using Bayes' theorem
P_Plant_I_Standard_Quality = (P_Standard_Quality_Plant_I * P_Plant_I) / P_Standard_Quality

print("Probability that the scooter came from Plant-I given it is of standard quality:", P_Plant_I_Standard_Quality)


Probability that the scooter came from Plant-I given it is of standard quality: 0.8395061728395061


Q11: A die was thrown 9000 times and of these 3220 yielded a 3 or 4. Can the die be regarded as
unbiased.



In [ ]:
#H_o = The die can be regarded as unbiased
#H_a = The die is biased

from scipy import stats

total_throws = 9000
observed_3_or_4 = 3220
alpha = 0.05

# Expected frequency for each outcome for a fair die
expected_frequency = total_throws * 2 / 6  # There are 2 favorable outcomes (3 and 4) out of 6 possible outcomes

chi_squared = ((observed_3_or_4 - expected_frequency) ** 2) / expected_frequency
degrees_of_freedom = 1  # Two categories (3 and 4) minus 1
p_value = 1 - stats.chi2.cdf(chi_squared, df=degrees_of_freedom)

if p_value < alpha:
    print("Reject Null Hypothesis: The die is biased.")
else:
    print("Fail to Reject Null Hypothesis: The die can be regarded as unbiased.")


Reject Null Hypothesis: The die is biased.


Q1.: Calculate the variance of the following data?

Class Interval

0-10 10-20 20-30 30-40 40-50 50-60 60-70

Frequency

8 12 10 8 3 2 7


In [ ]:
# Given data
class_interval = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70']
freq = [8, 12, 10, 8, 3, 2, 7]

midpoints = [(int(i.split('-')[0]) + int(i.split('-')[1])) / 2 for i in class_interval]

d = []
for j in range(len(class_interval)):
  d.extend([midpoints[j]] *freq[j])

print('Variance :',np.var(d))

Variance : 372.0


Q2: A manufacturer claimed that at least 95% of the equipment which he supplied to a factory
conformed to specifications. An examination of a sample of 200 pieces of equipment revealed that
18 were faulty. Test this claim at a significance level of 0.0.5 and 0.01.


In [ ]:
import scipy.stats as stats

sample_size = 200
faulty_count = 18
claimed_proportion = 0.05

#for alpha1 (0.05)
alpha1 = 0.05
result1 = stats.binomtest(faulty_count, n=sample_size, p=claimed_proportion, alternative='less')
p_value1 = result1.pvalue               #'less' indicates a one-tailed test where you are testing whether
                                        # the proportion of faulty equipment is less than the claimed proportion.

#for alpha2 (0.01)
alpha2 = 0.01
result2 = stats.binomtest(faulty_count, n=sample_size, p=claimed_proportion, alternative='less')
p_value2 = result2.pvalue

if p_value1 < alpha1:
    print("Reject Null Hypothesis at alpha =", alpha1)
    print("The proportion of faulty equipment is less than 5%.")
else:
    print("Fail to Reject Null Hypothesis at alpha =", alpha1)
    print("There is no significant evidence that the proportion is less than 5.")

if p_value2 < alpha2:
    print("\nReject Null Hypothesis at alpha =", alpha2)
    print("The proportion of faulty equipment is less than 5%.")
else:
    print("\nFail to Reject Null Hypothesis at alpha =", alpha2)
    print("There is no significant evidence that the proportion is less than 5.")

print("\nP-Value (alpha =", alpha1, "):", p_value1)
print("\nP-Value (alpha =", alpha2, "):", p_value2)


Fail to Reject Null Hypothesis at alpha = 0.05
There is no significant evidence that the proportion is less than 5.

Fail to Reject Null Hypothesis at alpha = 0.01
There is no significant evidence that the proportion is less than 5.

P-Value (alpha = 0.05 ): 0.9941764420322093

P-Value (alpha = 0.01 ): 0.9941764420322093


Q3.: A die is rolled 100 times with the following distribution:

Number

1 2 3 4 5 6


Observed frequency

17 14 20 17 17 15

At the 0.01 level of significance, determine whether die is true(or uniform)?(Hint : Use chi-square
test)


In [ ]:
import numpy as np
from scipy import stats

observed_frequencies = np.array([17, 14, 20, 17, 17, 15])
total_rolls = 100
alpha = 0.01

expected_frequencies = np.array([total_rolls/6] * 6)

chi_squared = np.sum((observed_frequencies - expected_frequencies)**2 / expected_frequencies)
degrees_of_freedom = len(observed_frequencies) - 1
p_value = 1 - stats.chi2.cdf(chi_squared, df=degrees_of_freedom)

if p_value < alpha:
    print("Reject Null Hypothesis: The die is not uniform (biased).")
else:
    print("Fail to Reject Null Hypothesis: The die is uniform (true).")


Fail to Reject Null Hypothesis: The die is uniform (true).


Q4: In a random sample of 400 persons from a large population,120 are females. Can it be said that
males and females are in the ration 5:3 in the population? Use 1% level of significance?


In [ ]:
import numpy as np
from scipy import stats

sample_size = 400
observed_females = 120
expected_ratio = 5/3
alpha = 0.01

expected_females = (expected_ratio / (1 + expected_ratio)) * sample_size
expected_males = sample_size - expected_females

standard_error = np.sqrt((expected_males * expected_females) / (sample_size**2 * (sample_size - 1)))
z_score = (observed_females - expected_females) / standard_error
critical_z = stats.norm.ppf(1 - alpha/2)

if abs(z_score) > critical_z:
    print("Reject Null Hypothesis: The ratio of males to females is not 5:3 in the population.")
else:
    print("Fail to Reject Null Hypothesis: The ratio of males to females is 5:3 in the population.")


Reject Null Hypothesis: The ratio of males to females is not 5:3 in the population.


In [ ]:
import statsmodels.api as sm

# Given sample size and observed frequencies
sample_size = 400
observed_females = 120

# Expected ratio of males to females in the population
expected_ratio = 5/3

# Perform the z-test for proportions
z_stat, p_value = sm.stats.proportions_ztest(observed_females, sample_size, value=1/expected_ratio)

# Two-tailed test, so we double the significance level for a one-tailed test (1% level)
alpha = 0.01

# Perform the hypothesis test
if abs(z_stat) > stats.norm.ppf(1 - alpha/2):
    print("Reject Null Hypothesis: The ratio of males to females is not 5:3 in the population.")
else:
    print("Fail to Reject Null Hypothesis: The ratio of males to females is 5:3 in the population.")


Reject Null Hypothesis: The ratio of males to females is not 5:3 in the population.


Q5: Find the Eigen values and Eigen Vectors of the matrix A.

A = [

2 0 1

0 2 0

1 0 2

]



In [ ]:
from numpy.linalg import eig

a = np.array([[2,0,1],[0,2,0],[1,0,2]])
value, vector = eig(a)

print('Eigen Value :\n',value)
print('\nEigen Vector :\n',vector)

Eigen Value :
 [3. 1. 2.]

Eigen Vector :
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]]


Q6.: Calculate the median, quartiles and the quartile coefficient of skewness from the following
data?

Weight

70-80 80-9- 90-100 100-110 110-120 120-130 130-140 140-150

No. of Persons:

12 18 35 42 50 45 20 8


In [ ]:
Weight = ['70-80', '80-90', '90-100', '100-110', '110-120', '120-130', '130-140', '140-150']
nu_person = [12, 18, 35, 42, 50, 45, 20, 8]

midpoint_0 = [((int(k.split('-')[0])) + (int(k.split('-')[1])))/2  for k in Weight]

data_0 = []
for i in range(len(Weight)):
  data_0.extend([midpoint_0[i]] * nu_person[i])

median = np.median(data_0)
Q1 = np.percentile(data_0, 25)
Q2 = np.percentile(data_0, 50)
Q3 = np.percentile(data_0, 75)
IQR = Q3 - Q1
QCS = (Q3 - median) - (median - Q1) / (Q3 - Q1)

print('Median :',median)
print('Quartile_1 :',Q1)
print('Quartile_2 :',Q2)
print('Quartile_3 :',Q3)
print('Inter Quartile Range (IQR) :',IQR)
print('Coefficient Of Skewness :',QCS)

Median : 115.0
Quartile_1 : 95.0
Quartile_2 : 115.0
Quartile_3 : 125.0
Inter Quartile Range (IQR) : 30.0
Coefficient Of Skewness : 9.333333333333334


Q7.: There are three bags: first containing 1 white, 2 red, 3 green balls; second containing 2 white, 3
red 1 green balls and third containing 3 white, 1 red and 2 green balls. Two balls are drawn from a
bag chosen at random. These are found to be one white and one red. Find the probability that the
balls so drawn came from the second bag.


In [ ]:
# Probabilities of choosing each bag
P_bag1 = 1/3
P_bag2 = 1/3
P_bag3 = 1/3

# Probabilities of drawing one white and one red ball from each bag
P_white_red_bag1 = (1/6) * (2/6)
P_white_red_bag2 = (2/6) * (3/6)
P_white_red_bag3 = (3/6) * (1/6)

# Total probability of drawing one white and one red ball
P_white_red = P_bag1 * P_white_red_bag1 + P_bag2 * P_white_red_bag2 + P_bag3 * P_white_red_bag3

# Conditional probability using Bayes' theorem
P_bag2_given_white_red = (P_bag2 * P_white_red_bag2) / P_white_red

print("Probability that the balls came from the second bag:", P_bag2_given_white_red)


Probability that the balls came from the second bag: 0.5454545454545454


Q8: The probability mass function of a variate X with the following distribution is given by
X 0 1 2 3 4 5 6
P(X) K 3k 5k 7k 9k 11k 13k
Find the value of k and P(X<4).


In [ ]:
from sympy import symbols, Eq, solve

# Define k as a symbol
k = symbols('k')

# Define the values of X
X_values = [0, 1, 2, 3, 4, 5, 6]

# Define the probabilities as a function of k
probabilities = [k, 3 * k, 5 * k, 7 * k, 9 * k, 11 * k, 13 * k]

# Create an equation to ensure the sum of probabilities equals 1
equation = Eq(sum(probabilities), 1)

# Solve for k
solutions = solve(equation, k)

# Check if there are valid solutions for k
if solutions:
    k_value = solutions[0]

    # Calculate P(X < 4)
    PX_less_than_4 = sum([prob.subs(k, k_value) for prob in probabilities[:4]])

    # Print the results
    print("Value of k:", k_value)
    print("P(X < 4):", PX_less_than_4)
else:
    print("No valid solution for k.")


Value of k: 1/49
P(X < 4): 16/49


Q9.: Find the Karl Persons Coefficient of Correlation for the following data:

x

105 104 102 101 100 99 98 96 93 92

y

101 103 100 98 95 96 104 92 97 94


In [ ]:
import numpy as np

x = [105, 104, 102, 101, 100, 99, 98, 96, 93, 92]
y = [101, 103, 100, 98, 95, 96, 104, 92, 97, 94]

print('Coefficient of Correlation :',round(np.corrcoef(x,y)[0,1],2))

Coefficient of Correlation : 0.6


Q10 find the mean of the following data?

Weight

0-10 10-20 20-30 30-40 40-50 50-60

No. of articles

14 17 22 26 23 18

In [ ]:
from statistics import mean, median, mode

weight = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60']
no_articles = [14, 17, 22, 26, 23, 18]

midpoint = [((int(k.split('-')[0])) + (int(k.split('-')[1])))/2  for k in weight]

data = []
for i in range(len(weight)):
  data.extend([midpoint[i]] * no_articles[i])

print('Mean :', mean(data))
print('Median :', median(data))
print('Mode :', mode(data))

Mean : 31.75
Median : 35.0
Mode : 35.0
